"""add_redaction_settings_tables

Revision ID: 19abad1933a6
Revises: 8a1b2c3d4e5f
Create Date: 2025-09-05 15:46:47.670339

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "19abad1933a6"
down_revision: str | Sequence[str] | None = "8a1b2c3d4e5f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "redaction_settings",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("file_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("show_all", sa.Boolean(), nullable=False),
        sa.Column("level_settings", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("revealed_items", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_shared", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["files.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_redaction_settings_file_user"),
        "redaction_settings",
        ["file_id", "user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_redaction_settings_shared"),
        "redaction_settings",
        ["is_shared", "created_at"],
        unique=False,
    )
    op.create_table(
        "redaction_settings_shares",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("settings_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "shared_with_user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "shared_with_team_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "permission_level", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["settings_id"],
            ["redaction_settings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_redaction_settings_shares_settings"),
        "redaction_settings_shares",
        ["settings_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_redaction_settings_shares_shared_with"),
        "redaction_settings_shares",
        ["shared_with_user_id", "shared_with_team_id"],
        unique=False,
    )
    # SQLiteでは一部のALTER COLUMN操作が制限されているため、スキップ
    # 新しいテーブル作成のみ実行
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_redaction_settings_shares_shared_with"),
        table_name="redaction_settings_shares",
    )
    op.drop_index(
        op.f("ix_redaction_settings_shares_settings"),
        table_name="redaction_settings_shares",
    )
    op.drop_table("redaction_settings_shares")
    op.drop_index(op.f("ix_redaction_settings_shared"), table_name="redaction_settings")
    op.drop_index(
        op.f("ix_redaction_settings_file_user"), table_name="redaction_settings"
    )
    op.drop_table("redaction_settings")
    # ### end Alembic commands ###
